# Generated by Django 2.2.18 on 2021-02-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kelas',
            options={'verbose_name_plural': '   Kelas'},
        ),
        migrations.AlterModelOptions(
            name='pasal',
            options={'verbose_name_plural': ' Pasal'},
        ),
        migrations.AlterModelOptions(
            name='pengajar',
            options={'verbose_name_plural': '    Pengajar'},
        ),
        migrations.AlterModelOptions(
            name='siswa',
            options={'verbose_name_plural': '  Siswa'},
        ),
        migrations.AddField(
            model_name='pelanggaran',
            name='pengajar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skor.Pengajar'),
        ),
        migrations.AlterField(
            model_name='pelanggaran',
            name='status',
            field=models.CharField(choices=[('Verifikasi', 'Verifikasi'), ('Terbukti', 'Terbukti'), ('Tidak Terbukti', 'Tidak Terbukti')], max_length=200, null=True),
        ),
    ]
