# Generated by Django 2.2.19 on 2021-02-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pengajar',
            name='jabatan',
        ),
        migrations.AddField(
            model_name='pengajar',
            name='jabatan',
            field=models.ManyToManyField(to='skor.Jabatan'),
        ),
    ]
