# Generated by Django 2.2.19 on 2021-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skor', '0002_auto_20210224_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jabatan',
            options={'verbose_name_plural': '     Jabatan'},
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='ayah',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='ibu',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='wali',
        ),
        migrations.AddField(
            model_name='pengajar',
            name='status',
            field=models.CharField(choices=[('PNS', 'PNS'), ('Guru Tidak Tetap', 'Guru Tidak Tetap'), ('Guru Honorer', 'Guru Honorer'), ('Lainnya', 'Lainnya')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='kelamin',
            field=models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=200, null=True),
        ),
    ]
