# Generated by Django 2.2.19 on 2021-02-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skor', '0003_auto_20210224_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jabatan',
            options={'verbose_name_plural': '      Jabatan'},
        ),
    ]
