# Generated by Django 2.2.19 on 2021-02-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skor', '0004_auto_20210224_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggaran',
            name='keterangan',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
